name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  Check:
    name: Run svelte-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install PNPM
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8

      - name: Install Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Retrieve pnpm store directory
        id: pnpm-store
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Configure pnpm store cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-store.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run svelte-check
        run: pnpm check

  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install PNPM
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8

      - name: Install Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Retrieve pnpm store directory
        id: pnpm-store
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Configure pnpm store cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-store.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - run: pnpm lint

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.15.1
          run_install: true
      - run: pnpm run test:unit
